### ISSUE TITLE
processProbaVbatch2: object 'patterns' not found

### ISSUE THREAD

**Issue by GreatEmerald** [JornDallinga/JornDallinga.github.io#4]
Trying to execute the processProbaVbatch2 function with multiple `x` results in an error:
```
 Error in list.files(x, pattern = pattern, recursive = T, include.dirs = F,  : 
  object 'patterns' not found
```

This is because the names `pattern` and `patterns` are used inconsistently in the function, both in the header and here: https://github.com/JornDallinga/JornDallinga.github.io/blob/master/R/processProbaVbatch2.R#L16
It should all be `pattern` and the default value should be set to something else (or nothing).

**Comment by JornDallinga** [comment]
fixed
