### ISSUE TITLE
getHarmMetricsSpatial: out_name is used but not defined

### ISSUE THREAD

**Issue by GreatEmerald** [JornDallinga/JornDallinga.github.io#7]
In https://github.com/JornDallinga/probaV/blob/master/R/getHarmMetricsSpatial.R#L77 the name `out_name` is used, but is not defined anywhere. And it's unclear how that is different from `filename`.

**Comment by JornDallinga** [comment]
I will add the out_name to the description of the function

**Comment by GreatEmerald** [comment]
How is it different from `filename`, though? Does it make sense to pass both, or just `out_name`?

**Comment by JornDallinga** [comment]
The Mc.Calc function uses both the filename and out_name (final result) variables within its function. Passing the out_name variable should be sufficient to generate the final result. 
In contrast, the calc::raster function uses 'filename' to write the final result, which is used within the Mc.Calc function.  I have not checked if this can be simplified without 'compromising' the original Mc.Calc function from the original ProbaV package. But it could be the reason why Johannes created 'out_name' for writing the final output. 

Let me know if you still run into errors when testing this function, or if I am overlooking your point.

**Comment by GreatEmerald** [comment]
Yes, this fixed the issue.
